input: samplesheet.csv
outdir: results
aligner: star_salmon
save_align_intermeds: true
save_unaligned: true
email: [email]
remove_ribo_rna: true
save_non_ribo_reads: true
save_trimmed: true
fasta: /home/[USER]/scratch/ref/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz
gtf: /home/[USER]/scratch/ref/Homo_sapiens.GRCh38.108.gtf.gz
hisat2_index: /home/[USER]/scratch/ref/genome/index/hisat2
gen_bed: /home/[USER]/scratch/ref/genome/Homo_sapiens.GRCh38.108.bed
transcript_fasta: /home/[USER]/scratch/ref/genome/genome.transcripts.fa
splicesites: /home/[USER]/scratch/ref/genome/index/Homo_sapiens.GRCh38.108.splice_sites.txt
rsem_index: /home/[USER]/scratch/ref/genome/rsem
salmon_index: /home/[USER]/scratch/ref/genome/index/salmon
save_reference: false
